import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

const Home: NextPage = () => {
  return (
    <div className="container">
      <Head>
        <title>Welcome to CEA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="m-auto">
        <h1 className="text-primary text-center">
          سلام گل
        </h1>
      </main>
    </div>
  )
}

export default Home
