import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import EventCard from "components/Cards/EventCard";
import NewsCard from "components/Cards/EventCard";
import MobileNewsCard from "components/Cards/MobileNewsCard";
import Layout from "components/Layout/Layout";
const Home: NextPage = () => {
  return (
    <div className="container">
      <Head>
        <title>Welcome to CEA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="m-auto">
        <Layout>
          <h1 className="text-primary text-center">سلام گل</h1>
          <MobileNewsCard eventData={"ss"} />
        </Layout>
      </main>
    </div>
  );
};

export default Home;
